### ISSUE TITLE
[windows] unknown symbol `__imp__sfListener_setPosition'

### ISSUE THREAD

**Issue by Shamar** [SFML-haskell/SFML-control#7] opened 2014-08-07 13:14 UTC
I can't build SFML-control on Windows (neither XP nor 7) since ghc complains about an unknown symbol `__imp__sfListener_setPosition'

Here some log

```
C:\Haskell\Projects\SFML-control>runhaskell Setup.hs build --verbose
Component build order: library
creating dist\build
creating dist\build\autogen
Building SFML-control-0.2.0.2...
Preprocessing library SFML-control-0.2.0.2...
Building library...
creating dist\build
C:\Haskell\Platform\bin\ghc.exe --make -fbuilding-cabal-package -O -outputdir dist\build -odir dist\build -hidir dist\build -stubdir dist\build -i -idist\build -isrc -idist\build\autogen -Idist\build\autogen -Idist\build -IC:\Libs\CSFML-2.0\include -IC:\Libs\SFML-2.0\include -optP-include -optPdist\build\autogen\cabal_macros.h -package-name SFML-control-0.2.0.2 -hide-all-packages -package-db dist\package.conf.inplace -package-id SFML-0.2.0.0-5c8b290db668284cc7eebe99aa35e3a2 -package-id base-4.6.0.1-f0c2cc6dcf0e12bf75312a2e7f354095 -package-id mtl-2.1.2-678980f6077e9f83a86186556aa2a425 -package-id template-haskell-2.8.0.0-42f1e6e55511ef4dff7e4249580faf8f -XHaskell2010 Control.Monad.SFML Control.Monad.SFML.Audio Control.Monad.SFML.Graphics Control.Monad.SFML.Window Control.Monad.SFML.System Control.Monad.SFML.Types Control.Monad.SFML.Types.TH Control.Monad.SFML.Types.Internal Control.Monad.SFML.Conversions 
[4 of 9] Compiling Control.Monad.SFML.Audio ( src\Control\Monad\SFML\Audio.hs, dist\build\Control\Monad\SFML\Audio.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.2 ... linking ... done.
Loading package SFML-0.2.0.0 ... linking ... ghc.exe: C:\Users\MyUser\AppData\Roaming\cabal\i386-windows-ghc-7.6.3\SFML-0.2.0.0\HSSFML-0.2.0.0.o: unknown symbol `__imp__sfListener_setPosition'
ghc.exe: unable to load package `SFML-0.2.0.0'
```

**Comment by adinapoli** [comment] 2014-08-14 19:08
Hi, sorry for reading this just now (was on holiday).
As you probably guessed, this is not SFML-control specific, but rather an SFML thing :)

I'll leave this open 'till it's clear what's going on.
Alfredo

**Comment by jeannekamikaze** [comment] 2014-08-14 21:34
My internet connection is back. Please allow me a day or two to solve all of your issues. This one is indeed a problem with SFML, and from the looks of it it's probably something stupid, like a function name change or the likes.

**Comment by adinapoli** [comment] 2014-08-15 07:55
No problem.
When you'll be ready and this issue will be dusted, it would be awesome to cut a new release on Hackage, so I can address https://github.com/SFML-haskell/SFML/issues/10 on my side :)

Furthermore (but requires a different issue), building SFML on GHC 7.8.3 is cumbersome, but is not entirely our fault, probably more a GHC issue. See here:

https://ghc.haskell.org/trac/ghc/ticket/9445#ticket

Alfredo

**Comment by Shamar** [comment] 2014-08-18 14:23
Any news? Currently I can't depend on SFML-control on Windows... (and I don't want to micromanage SFML's memory destroying objects).

**Comment by jeannekamikaze** [comment] 2014-08-18 14:54
I cannot replicate the problem on my end. From the looks of it, the function that is failing to link is exported by CSFML and used by the haskell SFML, so it seems like a problem with the way CSFML is built.

**Comment by jeannekamikaze** [comment] 2014-08-18 15:00
I am suspicious about that **imp** prefix on the unknown symbol on your end. Here, things are pretty simple. The haskell SFML has sfListener_setPosition undefined:

```
$ nm -gC libHSSFML-0.2.0.0.a | grep -i sfListener_setPosition
                 U sfListener_setPosition_helper
                 U sfListener_setPosition
0000000000000000 T sfListener_setPosition_helper
```

which is exported by CSFML as expected:

```
$ nm -gC libcsfml-audio.so | grep -i sfListener_setPosition
0000000000004aa0 T sfListener_setPosition
```

so everything works happily. Could you show me your output of `nm -gC foobar.so | grep sfListener` on the haskell library and csfml-audio?

**Comment by Shamar** [comment] 2014-08-18 15:13
```
$ nm -gC csfml-audio.lib | grep -i sfListener
00000000 I _imp__sfListener_getDirection
00000000 T sfListener_getDirection
00000000 I _imp__sfListener_getGlobalVolume
00000000 T sfListener_getGlobalVolume
00000000 I _imp__sfListener_getPosition
00000000 T sfListener_getPosition
00000000 I _imp__sfListener_setDirection
00000000 T sfListener_setDirection
00000000 I _imp__sfListener_setGlobalVolume
00000000 T sfListener_setGlobalVolume
00000000 I _imp__sfListener_setPosition
00000000 T sfListener_setPosition

$ nm -gC csfml-audio-2.dll | grep -i sfListener
61e41264 T sfListener_getDirection
61e4121c T sfListener_getGlobalVolume
61e4122c T sfListener_getPosition
61e4125c T sfListener_setDirection
61e41214 T sfListener_setGlobalVolume
61e41224 T sfListener_setPosition
```

**Comment by Shamar** [comment] 2014-08-18 15:26
Note that shared objects' equivalent in windows are DLL (dynamic link library).

These are from http://sfml-dev.org/download/sfml/2.0/ -> GCC 4.7 MinGW (DW2) - 32 bits

**Comment by Shamar** [comment] 2014-08-18 15:31
Here a few more info from the compiled SFML package from cabal:

```
$ nm -gC libHSSFML-0.2.0.0.a | grep -i sfListener
         U sfListener_getDirection_helper
         U sfListener_getGlobalVolume
         U sfListener_getPosition_helper
         U sfListener_setDirection_helper
         U sfListener_setGlobalVolume
         U sfListener_setPosition_helper
         U _imp__sfListener_getDirection
         U _imp__sfListener_getPosition
         U _imp__sfListener_setDirection
         U _imp__sfListener_setPosition
00000070 T sfListener_getDirection_helper
00000024 T sfListener_getPosition_helper
0000004c T sfListener_setDirection_helper
00000000 T sfListener_setPosition_helper

$ nm -gC HSSFML-0.2.0.0.o | grep -i sfListener
         U _imp__sfListener_getDirection
         U _imp__sfListener_getPosition
         U _imp__sfListener_setDirection
         U _imp__sfListener_setPosition
0006019c T sfListener_getDirection_helper
         U sfListener_getGlobalVolume
00060150 T sfListener_getPosition_helper
00060178 T sfListener_setDirection_helper
         U sfListener_setGlobalVolume
0006012c T sfListener_setPosition_helper
```

**Comment by Shamar** [comment] 2014-08-18 15:40
Actually, the difference here is that libHSSFML-0.2.0.0.a does not expose a _sfListener_setPosition_ function, but an __imp__sfListener_setPosition_ one. However I can see why.

**Comment by jeannekamikaze** [comment] 2014-08-18 15:40
It seems that the functions that are wrapped in the helpers are the ones causing trouble. They generate an external reference prefixed with _imp__, unlike the other functions that are called directly from haskell code. Given that your CSFML exports the functions prefixed with _imp__ as well, I wouldn't know where it's going wrong, however. I'd like to understand this whole _imp__ thing, it seems unnecessary.

**Comment by Shamar** [comment] 2014-08-18 15:45
Well, but here the problem is not the HSSFML package, but the **HSSFML-control** package.

It seems that while building SFML-control, ghc looks for _imp__sfListener_setPosition in the wrong place,

**Comment by jeannekamikaze** [comment] 2014-08-18 15:45
The imp prefix is just noting that the function is exported by a DLL. The whole symbol import/export table seems ok, but for some reason it's just failing to link. I haven't tested HSSFML on windows in ages, but it seems that last time I did I ended up compiling SFML/CSFML as a static library: https://github.com/SFML-haskell/SFML/wiki/Installation-on-Windows.

**Comment by jeannekamikaze** [comment] 2014-08-18 15:45
I am guessing this is a problem with the fact that SFML/CSFML are built as DLLs.

**Comment by Shamar** [comment] 2014-08-18 15:46
I tried that installation workflow too, without success.

**Comment by jeannekamikaze** [comment] 2014-08-18 15:50
Are the DLLs in your %PATH%?

**Comment by Shamar** [comment] 2014-08-18 15:51
Yes, they are.

**Comment by jeannekamikaze** [comment] 2014-08-18 16:06
And you are not mixing mingw installations, are you?

**Comment by Shamar** [comment] 2014-08-18 16:14
Mmm... what exactly you mean here? I've mingw installed from the latest official msi and the mingw from haskell platform in the path too.

**Comment by jeannekamikaze** [comment] 2014-08-18 16:15
That's exactly what I meant. Can you get rid of the standalone mingw package, make sure that the only gcc you have is the one from the haskell platform, and try again?

**Comment by Shamar** [comment] 2014-08-18 16:38
Nope... I tried with the standalone mingw package and it didn't worked. Then I tried with the Haskell Platform's one and didn't worked either.

**Comment by Shamar** [comment] 2014-08-19 07:48
I've found this GHC bug that **could** be related to this issue: https://ghc.haskell.org/trac/ghc/ticket/2283

It has been fixed in GHC 7.8.3, thus I'm downloading the haskell platform 2014.2 to test it.

Please tell me that SFML builds on GHC 7.8.3!

**Comment by adinapoli** [comment] 2014-08-19 09:13
It does build, but not without problems:

https://ghc.haskell.org/trac/ghc/ticket/9445

**Comment by Shamar** [comment] 2014-08-19 09:45
@adinapoli in that issue you set **MacOs X** as operating system.

**Comment by adinapoli** [comment] 2014-08-19 10:49
I know, but chances are the bug is platform independent. It was just to give you an hint in case you stumble upon it :)

**Comment by Shamar** [comment] 2014-08-20 08:27
Here my last attempt with GHC 7.8.3 (from Haskell Platform 2014.2.0.0):

```
C:\Haskell\Projects\SFML-control>nm -gC c:\Libs\lib\csfml-audio.lib|grep -i sfListener_setPosition
00000000 I _imp__sfListener_setPosition
00000000 T sfListener_setPosition

C:\Haskell\Projects\SFML-control>nm -gC c:\Libs\lib\csfml-audio.dll|grep -i sfListener_setPosition
61e41224 T sfListener_setPosition

C:\Haskell\Projects\SFML-control>nm -gC %APPDATA%\cabal\i386-windows-ghc-7.8.3\SFML-0.2.0.0\libHSSFML-0.2.0.0.a |grep sfListener_setPosition
         U sfListener_setPosition_helper
         U _imp__sfListener_setPosition
00000000 T sfListener_setPosition_helper

C:\Haskell\Projects\SFML-control>nm -gC %APPDATA%\cabal\i386-windows-ghc-7.8.3\SFML-0.2.0.0\HSSFML-0.2.0.0.o |grep sfListener_setPosition
         U _imp__sfListener_setPosition
00180228 T sfListener_setPosition_helper

C:\Haskell\Projects\SFML-control>cabal configure --extra-lib-dirs=c:\Libs\lib --extra-include-dirs=c:\Libs\include
Resolving dependencies...
Configuring SFML-control-0.2.0.2...

C:\Haskell\Projects\SFML-control>cabal build
Building SFML-control-0.2.0.2...
Preprocessing library SFML-control-0.2.0.2...
[1 of 9] Compiling Control.Monad.SFML.Types.Internal ( src\Control\Monad\SFML\Types\Internal.hs, dist\build\Control\Monad\SFML\Types\Internal.o )
[2 of 9] Compiling Control.Monad.SFML.Types.TH ( src\Control\Monad\SFML\Types\TH.hs, dist\build\Control\Monad\SFML\Types\TH.o )
[3 of 9] Compiling Control.Monad.SFML.Conversions ( src\Control\Monad\SFML\Conversions.hs, dist\build\Control\Monad\SFML\Conversions.o )
[4 of 9] Compiling Control.Monad.SFML.Audio ( src\Control\Monad\SFML\Audio.hs, dist\build\Control\Monad\SFML\Audio.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.3.1 ... linking ... done.
Loading package SFML-0.2.0.0 ... linking ... ghc.exe: C:\Users\GTesio.ORS\AppData\Roaming\cabal\i386-windows-ghc-7.8.3\SFML-0.2.0.0\HSSFML-0.2.0.0.o: unknown symbol `__imp__sfListener_setPosition'
ghc.exe: unable to load package `SFML-0.2.0.0'
```

I'm going to surrender.  :-(
The only thing that I noted is that ghc complains about an unknown symbol named ___imp__sfListener_setPosition_ starting with **two** underscores, while csfml-audio.lib provides __imp__sfListener_setPosition_, that starts with only **one** underscore.

**Comment by jeannekamikaze** [comment] 2014-08-20 09:22
The double underscore seems fine according to this thread: http://stackoverflow.com/questions/11236789/what-is-the-difference-between-imp-and-imp.

**Comment by jeannekamikaze** [comment] 2014-08-20 09:26
Also, what problems did you have with the build instructions on the wiki? When I tried the bindings on Windows I compiled SFML and CSFML with visual studio, not mingw. Have you tried the visual studio version of the library instead of the mingw one?

**Comment by Shamar** [comment] 2014-08-20 14:56
With the build instructions I had a few issues.

On CSFML, when I Hit Configure \ VisualStudio \ Finish I get this error:

```
CMake Error at src/SFML/CMakeLists.txt:26 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" (requested
  version 2) with any of the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Then, if I set CMAKE_MODULE_PATH to the CSFML-git\cmake\Module, I get this error:

```
CMake Error at cmake/Modules/FindSFML.cmake:307 (message):
  SFML found but some of its dependencies are missing ( FreeType GLEW libjpeg
  OpenAL libsndfile)
Call Stack (most recent call first):
  src/SFML/CMakeLists.txt:26 (find_package)
```

That's why I tried to use the official packages from http://sfml-dev.org/download/sfml/2.1/ (GCC 4.7 MinGW (DW2) - 32 bits) and http://www.sfml-dev.org/download/csfml/ (Visual C++ / GCC - 32 bits).

I choosed 32 bits (even if on a Windows 7 64bit machine) because I'd like to build a Haskell game that can run on a 32bit Windows XP too (my daughter's pc).

**Comment by adinapoli** [comment] 2014-08-20 15:08
As the second error implies, it seems that SFML was successfully found, and what's missing are other dependencies which needs to be installed separately. How hard would be to do that and retry the VisualC++ road?

**Comment by Shamar** [comment] 2014-08-20 15:28
It's a lot harder than you might think. Installing FreeType on windows for example, require MinGW, but to build HSSFML we have to use the MinGW provided by HaskellPlatform... After installing it via GnuWin32 setup (as described here: http://www.freetype.org/download.html), still CMake can't find it.

This is quite frustrating to me, but I could try **updated** and **detailed** build instructions for HSSFML, if you write them (even If I think that requiring VS is really too much).

**Comment by adinapoli** [comment] 2014-08-20 18:39
I'm afraid I can't help here, being a macosx user :(

**Comment by jeannekamikaze** [comment] 2014-08-20 18:49
I'm setting up the Haskell platform on a windows box, give me a sec.

**Comment by Shamar** [comment] 2014-08-20 18:54
@jeannekamikaze with ghc 7.8.3 the issue reported by @adinapoli is actually present on windows too.

Thus to compile HSSFML you will need to pass **--ghc-option=-fsimpl-tick-factor=1630** to cabal.

**Comment by Shamar** [comment] 2014-08-20 19:00
I'm wondering if the problem with HSSFML built with official SFML and CSFML packages is that HSSFML misses a FFI.h as described here: http://www.haskell.org/haskellwiki/GHC/Using_the_FFI#Including_the_FFI_header

**Comment by jeannekamikaze** [comment] 2014-08-20 19:12
So far I got HSSFML and the demos working using a 32-bit Haskell platform and the 32-bit mingw CSFML/SFML 2.1 libraries.

When I try to install SFML-control, I get the following error:

```
$ cabal install
Resolving dependencies...
Configuring SFML-control-0.2.0.2...
Building SFML-control-0.2.0.2...
Failed to install SFML-control-0.2.0.2
Last 10 lines of the build log ( C:\Users\jeanne\AppData\Roaming\cabal\logs\SFML-control-0.2.0.2.log ):
Loading package template-haskell ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.3.1 ... linking ... done.
Loading package SFML-0.2.0.0 ... ghc.exe: panic! (the 'impossible' happened)
  (GHC version 7.8.3 for i386-unknown-mingw32):
        loadArchive "C:\\Users\\jeanne\\Documents\\programming\\lib\\libcsfml-window.a": failed

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

ghc.exe: Unknown PEi386 section name `.idata$4' (while processing: C:\Users\jeanne\Documents\programming\lib\libcsfml-window.a)
cabal.exe: Error: some packages failed to install:
SFML-control-0.2.0.2 failed during the building phase. The exception was:
ExitFailure 1
PS C:\Users\jeanne\Documents\programming\SFML-control-master>
```

**Comment by jeannekamikaze** [comment] 2014-08-20 19:13
So here's the weird part: the demos are happy linking with the mingw version of SFML/CSFML, but SFML-control finds a weird section name in one of the libraries. What sense does this make?

**Comment by Shamar** [comment] 2014-08-20 19:15
I have seen this error too, I workaround it removing .a files and using the .lib ones

**Comment by jeannekamikaze** [comment] 2014-08-20 19:16
You mean using the visual studio version of the libraries instead of the mingw one? Let's try...

**Comment by Shamar** [comment] 2014-08-20 19:18
demos worked for me too, but when I tried building the SFML-control I got the initial error (that's why I open the bug to SFML-control from the beginning)

**Comment by jeannekamikaze** [comment] 2014-08-20 19:19
Because instructing your daughter in the ways of Linux and open source is not an option, right? Things are so much easier outside Windows land.

**Comment by Shamar** [comment] 2014-08-20 19:26
Lool! She is 5 years old! :-D
She already use Debian GNU/Linux on my workstation for games like frozen bubbles, that (requiring Perl) I don't want to install on her EeePC. But I can't install linux on her pc because it's also the only pc with windows (xp) at home.

And BTW, such huge friction on Windows is really weird. Haskell's support for Windows must be improved.

**Comment by jeannekamikaze** [comment] 2014-08-20 19:26
Did you get any error on ghc not finding the csfml DLLs?

**Comment by Shamar** [comment] 2014-08-20 19:30
Yes I got them too. As far as I can remember it was a %PATH% issue: you have to set the path envvar **and** use --extra-lib-dirs / --extra-include-dirs.

**Comment by jeannekamikaze** [comment] 2014-08-20 19:31
What I don't get is why HSSFML/demos work with both the mingw and VS versions of CSFML/SFML, while SFML-control only works (or at least gets to parse the .lib files correctly) with the VS version. If you can successfully link a binary against the SFML package, why would SFML-control fail?

**Comment by jeannekamikaze** [comment] 2014-08-20 19:32
They are on my path, and I passed them in --extra-lib-dirs. I had to rename the DLLs too, because it looks for csfml-window.dll instead of csfml-window-2.dll.

**Comment by jeannekamikaze** [comment] 2014-08-20 19:34
Ok I just had to restart the powershell. Now I got the __imp error you were getting.

**Comment by Shamar** [comment] 2014-08-20 19:35
Ah yes! Sorry, I tried so many things these days that I can't remember what fix what! :-D

That was the reason for my initial pull request. I noted that you added the default: False for the new flag, but this way cabal do not try all the value of the flag (I suppose).

**Comment by Shamar** [comment] 2014-08-20 19:42
SFML-control uses Template Haskell a lot: can this interfere with FFI?

**Comment by jeannekamikaze** [comment] 2014-08-20 19:53
Wait, since when do libraries have to link against other libraries? Linking is only done when building binaries. A library that depends on another library just needs the header files, then generates an undefined reference for every external function and lets the linker find stuff out later when building the actual binary. I don't see why building SFML-control causes ghc to inspect the .o file for HSSFML. It is as if it were trying to solve HSSFML's undefined references beforehand and failing to do so. And on top of that I don't see why it fails, since the symbol it complains about is indeed exported by the lib/DLL pair. And then again, everything works fine when building the demos. There is certainly something weird here, it doesn't make sense that ghc links everything successfully on one hand, and on the other hand complains about unknown section names and symbols that are indeed exported.

**Comment by Shamar** [comment] 2014-08-20 20:12
@jeannekamikaze @adinapoli I'm not sure, but as far as I understood, Template Haskell expressions are resolved at compile time. But how can it lift SFML.Audio at compile time, without inspecting HSSFML.o?

**Comment by jeannekamikaze** [comment] 2014-08-20 20:33
I don't know, I have never written any template Haskell. Perhaps it looks at the .o file to match function signatures, but I don't see why it would attempt resolving an undefined reference coming from a C library.

**Comment by Shamar** [comment] 2014-08-20 23:23
@adinapoli I guess that the TH Name provided by https://github.com/SFML-haskell/SFML-control/blob/master/src/Control/Monad/SFML/Audio.hs#L15 is __imp__sfListener_setPosition, and such name is passed to reify (https://hackage.haskell.org/package/template-haskell-2.8.0.0/docs/Language-Haskell-TH.html#g:4) that inspects this HSSFML.o.

Can you verify this hypothesis in any way?

**Comment by adinapoli** [comment] 2014-08-21 07:11
Uhm, it seems strange to me; lifting here is just a TH sugar for taking the original _Haskell_ function name, so I would be extremely surprised of the contrary.

If you want to inspect function names during compile time, it should be sufficient to hack this line:

https://github.com/SFML-haskell/SFML-control/blob/master/src/Control/Monad/SFML/Types/TH.hs#L68

And use "runIO . print" before it, to actually show what has been passed to reify.
I would expect it to show the original HSSFML name, in this case : 

https://github.com/SFML-haskell/SFML/blob/master/src/SFML/Audio/Listener.hs#L54

A different point might be that reify, when building its `Info` data structure, is traversing the whole Haskell stack up to HSSFML.o, but I genuinely have no clue about reify implementation, so we should probably ask to the Haskell Cafe if this might be the case.

Last but not least, what happens if you comment out that troublesome line? (Audio.hs#15).
If the problem is generalised on how TH inspect things, you should receive another error on another symbol. If the installation goes through instead, it might suggest it's a corner case specific to that function, which might or might not give us some extra insight.

**Comment by Shamar** [comment] 2014-08-21 09:17
Nope. Adding "runIO . print" doesn't produce anything. I'm getting the initial error again.
Removing (Audio.hs#15) does not change anything.

**Comment by adinapoli** [comment] 2014-08-21 12:22
That's quite interesting then, because it means reify is not the cause here, and "runIO . print $ name" is not producing anything because is probably not being called. In other terms, the compile error happens before that line.

**Comment by jeannekamikaze** [comment] 2015-09-23 08:16
Got this working on Windows. Should work for you with the new installation instructions.

**Comment by adinapoli** [comment] 2015-09-23 08:17
:tada: Nice job!

**Comment by jeannekamikaze** [comment] 2015-09-23 08:26
Closing, please re-open if issue persists.

**Closed as completed by jeannekamikaze** 2015-09-23 08:26 UTC
